#!/usr/bin/env python3
"""Export Evergreen DB to a Lakebed capsule and deploy it."""

import json
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from evergreen.db import get_connection

LAKEBED_DIR = Path(__file__).resolve().parent.parent / "lakebed"
DATA_FILE = LAKEBED_DIR / "client" / "data.ts"


def query(sql, params=()):
    conn = get_connection()
    conn.row_factory = lambda c, r: dict(zip([col[0] for col in c.description], r))
    rows = conn.execute(sql, params).fetchall()
    conn.close()
    return rows


def scalar(sql):
    conn = get_connection()
    val = conn.execute(sql).fetchone()[0]
    conn.close()
    return val


def export_data():
    bugs = query(
        "SELECT id, created_at, environment, severity, summary, probable_root_cause, "
        "pr_url, pr_status, status, occurrence_count "
        "FROM bugs ORDER BY created_at DESC"
    )
    # alerts/runs are capped to the most recent rows to keep the deployed Lakebed
    # artifact under its 2 MiB request limit (aggregate stats below still count the
    # full tables). Bugs are kept in full — there are far fewer of them.
    alerts = query(
        "SELECT id, created_at, source, source_url, cve, name, severity, "
        "affected_component, summary, impact_assessment, pr_url, pr_status, status "
        "FROM security_alerts ORDER BY created_at DESC LIMIT 120"
    )
    runs = query(
        "SELECT id, started_at, finished_at, type, summary, cost, tokens, model, effort "
        "FROM runs ORDER BY started_at DESC LIMIT 120"
    )
    cost_by_skill = query(
        "SELECT replace(type, 'cron:', '') as skill, "
        "ROUND(SUM(cost), 2) as cost, COUNT(*) as runs, ROUND(AVG(cost), 3) as avg_cost "
        "FROM runs WHERE cost IS NOT NULL GROUP BY skill ORDER BY cost DESC"
    )

    conn = get_connection()
    stats = {
        "bugs_open": conn.execute("SELECT COUNT(*) FROM bugs WHERE status NOT IN ('resolved','not_actionable')").fetchone()[0],
        "bugs_resolved": conn.execute("SELECT COUNT(*) FROM bugs WHERE status='resolved'").fetchone()[0],
        "alerts_actionable": conn.execute("SELECT COUNT(*) FROM security_alerts WHERE status IN ('new','in_progress')").fetchone()[0],
        "alerts_cleared": conn.execute("SELECT COUNT(*) FROM security_alerts WHERE status IN ('not_affected','not_actionable','resolved')").fetchone()[0],
        "total_runs": conn.execute("SELECT COUNT(*) FROM runs").fetchone()[0],
        "timeouts": conn.execute("SELECT COUNT(*) FROM runs WHERE summary LIKE 'TIMEOUT%'").fetchone()[0],
        "cost_total": round(conn.execute("SELECT COALESCE(SUM(cost), 0) FROM runs").fetchone()[0], 2),
        "cost_7d": round(conn.execute(
            "SELECT COALESCE(SUM(cost), 0) FROM runs "
            "WHERE started_at > cast(strftime('%s','now') as integer) - 604800"
        ).fetchone()[0], 2),
        "prs_open": (
            conn.execute("SELECT COUNT(*) FROM bugs WHERE pr_url IS NOT NULL AND pr_status='open'").fetchone()[0]
            + conn.execute("SELECT COUNT(*) FROM security_alerts WHERE pr_url IS NOT NULL AND pr_status='open'").fetchone()[0]
        ),
        "prs_merged": (
            conn.execute("SELECT COUNT(*) FROM bugs WHERE pr_url IS NOT NULL AND pr_status='merged'").fetchone()[0]
            + conn.execute("SELECT COUNT(*) FROM security_alerts WHERE pr_url IS NOT NULL AND pr_status='merged'").fetchone()[0]
        ),
        "prs_closed": (
            conn.execute("SELECT COUNT(*) FROM bugs WHERE pr_url IS NOT NULL AND pr_status='closed'").fetchone()[0]
            + conn.execute("SELECT COUNT(*) FROM security_alerts WHERE pr_url IS NOT NULL AND pr_status='closed'").fetchone()[0]
        ),
    }
    conn.close()

    daily = {
        "runs": query("SELECT date(started_at,'unixepoch','localtime') as day, COUNT(*) as n FROM runs WHERE started_at IS NOT NULL GROUP BY day ORDER BY day"),
        "bugs": query("SELECT date(created_at,'unixepoch','localtime') as day, COUNT(*) as n FROM bugs GROUP BY day ORDER BY day"),
        "prs": query("SELECT date(created_at,'unixepoch','localtime') as day, COUNT(*) as n FROM bugs WHERE pr_url IS NOT NULL GROUP BY day ORDER BY day"),
        "threats": query("SELECT date(created_at,'unixepoch','localtime') as day, COUNT(*) as n FROM security_alerts GROUP BY day ORDER BY day"),
    }

    from datetime import datetime
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    return bugs, alerts, runs, stats, daily, cost_by_skill, now


TYPES = """\
// Generated by deploy-lakebed.py — do not edit manually

export type Bug = {
  id: number;
  created_at: number;
  environment: string;
  severity: string;
  summary: string;
  probable_root_cause: string | null;
  pr_url: string | null;
  pr_status: string | null;
  status: string;
  occurrence_count: number;
};

export type Alert = {
  id: number;
  created_at: number;
  source: string;
  source_url: string | null;
  cve: string | null;
  name: string | null;
  severity: string;
  affected_component: string | null;
  summary: string;
  impact_assessment: string | null;
  pr_url: string | null;
  pr_status: string | null;
  status: string;
};

export type Run = {
  id: number;
  started_at: number;
  finished_at: number | null;
  type: string;
  summary: string | null;
  cost: number | null;
  tokens: number | null;
  model: string | null;
  effort: string | null;
};

export type Stats = {
  bugs_open: number;
  bugs_resolved: number;
  alerts_actionable: number;
  alerts_cleared: number;
  total_runs: number;
  timeouts: number;
  cost_total: number;
  cost_7d: number;
  prs_open: number;
  prs_merged: number;
  prs_closed: number;
};

export type CostBySkill = {
  skill: string;
  cost: number;
  runs: number;
  avg_cost: number;
};

export type DailyEntry = { day: string; n: number };

export type DailyActivity = {
  runs: DailyEntry[];
  bugs: DailyEntry[];
  prs: DailyEntry[];
  threats: DailyEntry[];
};
"""


def write_data_ts(bugs, alerts, runs, stats, daily, cost_by_skill, now):
    lines = [TYPES]
    lines.append(f"export const bugs: Bug[] = {json.dumps(bugs, separators=(',', ':'))};")
    lines.append(f"export const alerts: Alert[] = {json.dumps(alerts, separators=(',', ':'))};")
    lines.append(f"export const runs: Run[] = {json.dumps(runs, separators=(',', ':'))};")
    lines.append(f"export const stats: Stats = {json.dumps(stats, separators=(',', ':'))};")
    lines.append(f"export const daily: DailyActivity = {json.dumps(daily, separators=(',', ':'))};")
    lines.append(f"export const costBySkill: CostBySkill[] = {json.dumps(cost_by_skill, separators=(',', ':'))};")
    lines.append(f'export const lastUpdated = "{now}";')
    lines.append("")
    DATA_FILE.write_text("\n".join(lines))
    print(f"Wrote {DATA_FILE} ({DATA_FILE.stat().st_size} bytes)")


def git_commit():
    subprocess.run(["git", "add", "-A"], cwd=LAKEBED_DIR, check=True)
    result = subprocess.run(["git", "diff", "--cached", "--quiet"], cwd=LAKEBED_DIR)
    if result.returncode == 0:
        print("No changes to commit")
        return False
    subprocess.run(
        ["git", "commit", "-m", "Update dashboard data"],
        cwd=LAKEBED_DIR, check=True, capture_output=True,
    )
    print("Committed changes")
    return True


def deploy():
    print("Deploying to Lakebed...")
    result = subprocess.run(
        ["npx", "lakebed", "deploy"],
        cwd=LAKEBED_DIR, capture_output=True, text=True, timeout=60,
    )
    print(result.stdout)
    if result.stderr:
        print(result.stderr, file=sys.stderr)
    if result.returncode != 0:
        print(f"Deploy failed (exit {result.returncode})", file=sys.stderr)
        sys.exit(1)


def main():
    print("Exporting Evergreen DB...")
    bugs, alerts, runs, stats, daily, cost_by_skill, now = export_data()
    print(f"  {len(bugs)} bugs, {len(alerts)} alerts, {len(runs)} runs")
    write_data_ts(bugs, alerts, runs, stats, daily, cost_by_skill, now)
    changed = git_commit()
    if changed:
        deploy()
    else:
        print("Data unchanged, skipping deploy")


if __name__ == "__main__":
    main()
